# Generated by Django 3.1.6 on 2021-03-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_added_portfolio_and_trades'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='current_amount',
            field=models.DecimalField(decimal_places=2, default=200000, max_digits=9),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='starting_amount',
            field=models.DecimalField(decimal_places=2, default=200000, max_digits=9),
        ),
    ]
