# Generated by Django 3.1.6 on 2021-04-24 18:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_added_portfolio_amount_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='trade_made_day',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 4, 24, 18, 45, 21, 849932)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trade',
            name='buy_date',
            field=models.DateField(),
        ),
    ]
